### ISSUE TITLE
IndexError: list index out of range using $speed on audio

### ISSUE THREAD

**Issue by HexCodeFFF** [HexCodeFFF/captionbot#12]
```
DATETIME:2021-04-01 18:02:42.261900
COMMAND:$speed 2
TRACEBACK:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 785, in spcommand
    await improcess(ctx, improcessing.speed, [["VIDEO", "GIF"]], speed)
  File "main.py", line 320, in improcess
    raise e
  File "main.py", line 302, in improcess
    result = await func(filesforcommand, *args)
  File "/home/hex/Desktop/captionbot/improcessing.py", line 543, in speed
    fps = await get_frame_rate(file)
  File "/home/hex/Desktop/captionbot/improcessing.py", line 152, in get_frame_rate
    rate = out.split('=')[1].strip()[1:-1].split('/')
IndexError: list index out of range```

**Comment by HexCodeFFF** [comment]
fixed with closing of #19 , since $speed doesnt accept audio by default
