### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''; 

### ISSUE THREAD

**Issue by HexCodeFFF** [HexCodeFFF/captionbot#13]
```
DATETIME:2021-03-31 20:33:39.181706
COMMAND:$freezemotivateaudio HOLY SHOOT!|shostakovich copyed mom three!!!!
TRACEBACK:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 525, in freezemotivateaudio
    await improcess(ctx, improcessing.freezemotivate, [["VIDEO", "GIF"], ["AUDIO"]], *caption)
  File "main.py", line 320, in improcess
    raise e
  File "main.py", line 302, in improcess
    result = await func(filesforcommand, *args)
  File "/home/hex/Desktop/captionbot/improcessing.py", line 790, in freezemotivate
    framecount = int(framecount)
ValueError: invalid literal for int() with base 10: ''
```
![image](https://user-images.githubusercontent.com/35177464/113362909-1b817f80-9315-11eb-87b0-2b5907817e2f.png)

the bot replied to the same message 3 fucking times

**Comment by HexCodeFFF** [comment]
same bug occured here
https://ptb.discord.com/channels/803788965215338546/803806089237889025/826715909242355753
https://ptb.discord.com/channels/803788965215338546/803806089237889025/826992678239076352

**Comment by HexCodeFFF** [comment]
improperly handled error that shouldn't occur with the closing of #19
