### ISSUE TITLE
OSError: image file is truncated (11 bytes not processed); bug in $sus

### ISSUE THREAD

**Issue by HexCodeFFF** [HexCodeFFF/captionbot#14]
```DATETIME:2021-03-31 15:43:51.527153
COMMAND:$sus when the impooooooooooooooooster is sus!ðŸ˜³
TRACEBACK:
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/hex/Desktop/captionbot/improcessing.py", line 51, in pass_temp_session
    result = fn(*args, **kwargs)
  File "/home/hex/Desktop/captionbot/sus.py", line 91, in sus
    letter = master_im.crop((x_coords[0], 0, x_coords[1], y_coord_split))
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 1127, in crop
    self.load()
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFile.py", line 259, in load
    raise OSError(
OSError: image file is truncated (11 bytes not processed)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 1000, in jermatext
    await improcess(ctx, sus.sus, [], text)
  File "main.py", line 320, in improcess
    raise e
  File "main.py", line 304, in improcess
    result = await renderpool.submit(func, *args)
  File "/home/hex/Desktop/captionbot/improcessing.py", line 70, in submit
    return await fut
OSError: image file is truncated (11 bytes not processed)```

**Comment by HexCodeFFF** [comment]
probably closed but if it could be reproduced it'd be nice
