### ISSUE TITLE
Message: invalid session id

### ISSUE THREAD

**Issue by enchanted-sword** [HexCodeFFF/captionbot#27]
**Describe the bug**
Error message when using $freezemotivate on this gif:
https://tenor.com/view/nekohime-anime-drink-hot-drink-gif-14698957

**Screenshots**
![image](https://user-images.githubusercontent.com/81981111/116483868-52887980-a85e-11eb-8ba9-54d5e29f0f7c.png)

**Traceback**
DATETIME:2021-04-28 18:12:11.238543
COMMAND:$freezemotivate why is she drinking|piss
TRACEBACK:
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/hex/Desktop/captionbot/improcessing.py", line 52, in pass_temp_session
    result = fn(*args, **kwargs)
  File "/home/hex/Desktop/captionbot/captionfunctions.py", line 90, in motivate
    return htmlcap("captionhtml/motivate.html", image, caption, tosavename)
  File "/home/hex/Desktop/captionbot/captionfunctions.py", line 63, in htmlcap
    chromiumrender.html2png(torender, tosavename)
  File "/home/hex/Desktop/captionbot/chromiumrender.py", line 98, in html2png
    driver.set_window_size(1, 1)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 1090, in set_window_size
    self.set_window_rect(width=int(width), height=int(height))
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 1180, in set_window_rect
    return self.execute(Command.SET_WINDOW_RECT, {"x": x, "y": y,
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 521, in freezemotivate
    await improcess(ctx, improcessing.freezemotivate, [["VIDEO", "GIF"]], *caption)
  File "main.py", line 332, in improcess
    raise e
  File "main.py", line 314, in improcess
    result = await func(filesforcommand, *args)
  File "/home/hex/Desktop/captionbot/improcessing.py", line 795, in freezemotivate
    clastframe = await handleanimated(lastframe, captionfunctions.motivate, None, *caption)
  File "/home/hex/Desktop/captionbot/improcessing.py", line 401, in handleanimated
    result = await renderpool.submit(capfunction, media, caption)
  File "/home/hex/Desktop/captionbot/improcessing.py", line 71, in submit
    return await fut
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id

**Comment by HexCodeFFF** [comment]
This bug has to do with linux sometimes killing the chrome sessions that mediaforge uses. not going to close this yet cause i want to make a permanent fix but a reboot of the bot should temporarfily fix this.
